language: node_js
# nodejs版本
node_js: stable
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install
before_script:
  
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - echo "utrydesign" > CNAME
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update website"
  - git push --force --quiet "https://${test_token}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle
branches:
  only:
    - 0.1
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   - GH_REF: github.com/philcui/philcui.github.io.pcvue.git
   - U_NAME: philcui
   - U_EMAIL: cuixihang@126.com
   - P_BRANCH: gh-pages